### ISSUE TITLE
Duplicate keys not set correctly on maps

### ISSUE THREAD

**Issue by dolphinspired** [peposso/lua-tinyyaml#8]
The bit of code that handles duplicate keys in maps has a small typo that prevents it from working correctly, seen [here](https://github.com/peposso/lua-tinyyaml/blob/master/tinyyaml.lua#L647). That `__` (double-underscore) should be `_` (single-underscore). As a result, duplicates keys in yaml maps always get assigned to `name_1`.

```yaml
map:
  Fruit: apple  # --> "Fruit"
  Fruit: orange # --> "Fruit_1"
  Fruit: banana # --> "Fruit_1" again, overwriting previous value
```

In addition, flow-style maps handle duplicates differently:

```yaml
map: { Fruit: apple, Fruit: orange, Fruit: banana } # --> Fruit = banana, ignores duplicates
```
